//! One-time migration of the config graph out of the combined store (contreforts-workspace#58,
//! D8 part 2a).
//!
//! # Why this exists
//!
//! Today one Oxigraph store holds both graphs for a user: `contreforts-core::GraphConfig`'s
//! combined `graph_store`, with configuration living inside it under the named graph
//! `contreforts_core::namespaces::CONFIG_GRAPH`. D2 gave configuration its own store, at
//! `<os-data-dir>/config_store` -- on every existing deployment, an **empty** directory. The
//! moment part 2b rewires consumers onto `ConfigStore`, every company, connector, credential,
//! knowledge base and agent a user hand-entered would appear to have vanished, because nothing
//! has ever copied that data across. Unlike knowledge-graph data (regenerated by the next sync),
//! configuration is hand-entered and not re-derivable -- the exact asymmetry D2's own doc comment
//! on `ConfigStoreConfig` already states as the reason the config store keeps no
//! current-working-directory fallback the combined store still has.
//!
//! The repo owner's ruling for this piece, communicated directly for D8 part 2a (not yet folded
//! into contreforts-workspace#58's issue text as of this writing): migrate once, loudly, and
//! verify. On startup, if the config store is empty *and* the combined store holds a config
//! graph, copy it across, and refuse to proceed if the copy is incomplete. No operator action,
//! nothing silent, nothing lost.
//!
//! # What this file pins
//!
//! `contreforts_config::migrate_config_graph_if_needed` and
//! `contreforts_config::verify_config_graph_copy` do not exist yet -- this file does not compile
//! against `develop`. That is the sanctioned RED (`crates/contreforts-kg/CONTRIBUTING.md` §3): a
//! compile error naming the missing items is evidence enough.
//!
//! `migrate_config_graph_if_needed(combined_store_path, config_store)` is the entry point part
//! 2b's startup wiring calls, once, before any consumer touches `config_store`. It opens
//! `combined_store_path` itself (this crate has no dependency on `contreforts-kg`, and does not
//! need one here -- the combined store is a plain Oxigraph on-disk store, exactly like this
//! crate's own [`contreforts_config::ConfigStore`]) and returns a [`contreforts_config::MigrationOutcome`]
//! describing what happened, never silently. `verify_config_graph_copy(source, config_store)` is
//! the verification primitive `migrate_config_graph_if_needed` calls internally right after
//! copying -- exposed separately so it can be pinned directly against a deliberately incomplete
//! target, rather than trusting the copy step's own correctness (this file's own trap warning).
//!
//! # Fixture note
//!
//! Every IRI below is a full bracketed `<...>` (via `NamedNode::new`) or built through
//! `contreforts_core::namespaces`' own builders -- never a raw `/` in a prefixed-name local part.
//!
//! Gated behind the `legacy-combined-store-migration` Cargo feature (off by default): fabricating
//! the fixture "combined store" below needs oxigraph's RocksDB backend, which this crate
//! otherwise no longer links (see `src/persistence.rs`'s module doc). Run with
//! `cargo test -p contreforts-config --features legacy-combined-store-migration`.
#![cfg(feature = "legacy-combined-store-migration")]

use std::collections::BTreeSet;
use std::path::Path;

use contreforts_config::{
    AgentConfig, ChannelRef, CompanyConfig, ConfigGraph, ConfigStore, ForgejoConnectorConfig,
    KgInstanceConfig, KnowledgeBaseConfig, MigrationOutcome, migrate_config_graph_if_needed,
    verify_config_graph_copy,
};
use contreforts_core::namespaces::{CONFIG_GRAPH, CORE_NS};
use contreforts_declaration::ConnectorDeclarations;
use oxigraph::model::{GraphName, Literal, NamedNode, Quad, Term};
use oxigraph::store::Store;

const KG_INSTANCE_PREFIX: &str = "https://contreforts.ds-labs.org/data/instance/migrate-9c3f/";

fn config_store_at(path: &Path) -> ConfigStore {
    ConfigStore::open(path).expect("config store opens at a fresh path")
}

/// All CONFIG_GRAPH triples in `store`, as plain `(subject, predicate, object)` display strings
/// -- deliberately not just a count, so a migration that copies the first subject and stops (or
/// copies the right *number* of triples but the wrong *content*) is caught by set equality, not
/// hidden by a coincidentally matching length.
fn config_graph_triples(store: &Store) -> BTreeSet<(String, String, String)> {
    let graph = NamedNode::new(CONFIG_GRAPH).expect("CONFIG_GRAPH is a valid IRI");
    store
        .quads_for_pattern(None, None, None, Some((&graph).into()))
        .map(|q| {
            let q = q.expect("reading a quad back from the store succeeds");
            (
                q.subject.to_string(),
                q.predicate.to_string(),
                q.object.to_string(),
            )
        })
        .collect()
}

fn distinct_subjects(triples: &BTreeSet<(String, String, String)>) -> BTreeSet<&str> {
    triples.iter().map(|(s, _, _)| s.as_str()).collect()
}

/// Whether `n` appears in `message` as a standalone number (split on non-digit characters),
/// rather than merely as a substring of a larger number -- e.g. so a check for `10` is not
/// satisfied by a message that only ever mentions `100`.
fn message_contains_number(message: &str, n: usize) -> bool {
    let target = n.to_string();
    message
        .split(|c: char| !c.is_ascii_digit())
        .any(|tok| tok == target)
}

/// Every quad anywhere in `store`, regardless of graph -- used by the "only the config graph
/// moves" test to prove a KG-data triple is absent from the *whole* target, not merely absent
/// from the graph name it happened to have in the source.
fn all_quads(store: &Store) -> Vec<Quad> {
    store
        .quads_for_pattern(None, None, None, None)
        .collect::<Result<Vec<_>, _>>()
        .expect("reading every quad back from the store succeeds")
}

/// Builds a combined store at `path` carrying several config record kinds -- a company, a
/// (label-scoped) connector, a KG instance, a knowledge base naming that instance, and an agent
/// -- plus one genuine knowledge-graph-data triple living under a *different* named graph, the
/// way today's real combined store does (`contreforts-core::GraphConfig`'s own doc comment: "a
/// single Oxigraph store holds both graphs for one user"). Item 1's own warning -- "a migration
/// that copies the first subject and stops must fail this" -- is exactly why this fixture uses
/// five distinct config subjects rather than one.
///
/// The triples themselves are generated through `contreforts_config::ConfigGraph` (against a
/// throwaway, in-memory-backed `ConfigStore`), so their shape can never drift from what the real
/// engine writes -- but `path` itself ends up a genuine RocksDB-backed `oxigraph::store::Store`,
/// matching what a real legacy combined store looks like on disk. `contreforts_config::ConfigStore`
/// is no longer RocksDB-backed itself (`src/persistence.rs`), so it can no longer double as this
/// fixture's own on-disk format the way it once did -- `open_store` (what
/// `migrate_config_graph_if_needed` actually reads `path` with) needs RocksDB there for real.
///
/// Returns the exact CONFIG_GRAPH triple set written, so callers can assert the migrated content
/// against it directly rather than re-deriving it.
fn build_combined_store(path: &Path) -> BTreeSet<(String, String, String)> {
    let scratch_dir = tempfile::tempdir().expect("tempdir for the fixture-generating scratch store");
    let store = config_store_at(&scratch_dir.path().join("scratch"));
    let cg = ConfigGraph::new(&store, ConnectorDeclarations::none());

    cg.set_kg_instance(&KgInstanceConfig {
        label: "primary".to_string(),
        iri_prefix: KG_INSTANCE_PREFIX.to_string(),
        datadir: Some("/var/lib/contreforts/kg-instances/migrate-primary".to_string()),
    })
    .expect("registering the KG instance succeeds");

    cg.add_company(&CompanyConfig {
        slug: "acme".to_string(),
        name: "Acme".to_string(),
    })
    .expect("company registers cleanly");

    cg.set_forgejo_connector(
        "acme",
        &ForgejoConnectorConfig {
            label: "main".to_string(),
            url: "https://git.example.com".to_string(),
            token: "secret-token".to_string(),
        },
    )
    .expect("connector registers cleanly");

    let kb_graph = format!("{KG_INSTANCE_PREFIX}kb/support");
    cg.set_knowledge_base(
        "acme",
        &KnowledgeBaseConfig {
            label: "support".to_string(),
            kg_instance_label: Some("primary".to_string()),
            graph: Some(kb_graph.clone()),
            vector_store_label: "vs".to_string(),
        },
    )
    .expect("knowledge base registers cleanly");

    cg.set_agent(
        "acme",
        &AgentConfig {
            label: "helper".to_string(),
            display_name: Some("Helper".to_string()),
            knowledge_base_label: "support".to_string(),
            channels: vec![ChannelRef {
                kind: "email".to_string(),
                label: "support-inbox".to_string(),
            }],
        },
    )
    .expect("agent registers cleanly");

    // The other half of the combined store: real knowledge-graph data, indexed under the KB's
    // own graph IRI -- *not* CONFIG_GRAPH. This is the data item 6 requires must never reach the
    // config store.
    store
        .inner()
        .insert(&Quad::new(
            NamedNode::new(format!("{kb_graph}#doc-1")).expect("doc IRI is valid"),
            NamedNode::new(format!("{CORE_NS}title")).expect("predicate IRI is valid"),
            Term::Literal(Literal::new_simple_literal(
                "A real knowledge-base document, not configuration",
            )),
            GraphName::NamedNode(NamedNode::new(&kb_graph).expect("kb graph IRI is valid")),
        ))
        .expect("inserting the KG-data triple succeeds");

    let triples = config_graph_triples(store.inner());
    let fixture_quads = all_quads(store.inner());
    drop(store);

    let combined = Store::open(path).expect("opening the RocksDB-backed combined-store fixture");
    for quad in fixture_quads {
        combined
            .insert(&quad)
            .expect("copying a fixture quad into the combined store");
    }
    drop(combined);

    triples
}

/// A single quad, matching the shape `build_combined_store`'s own KG-data insert uses, so tests
/// that check for its *absence* in the target are checking for the exact triple that exists in
/// the source -- not a coincidentally similar one.
fn kg_data_quad() -> Quad {
    let kb_graph = format!("{KG_INSTANCE_PREFIX}kb/support");
    Quad::new(
        NamedNode::new(format!("{kb_graph}#doc-1")).expect("doc IRI is valid"),
        NamedNode::new(format!("{CORE_NS}title")).expect("predicate IRI is valid"),
        Term::Literal(Literal::new_simple_literal(
            "A real knowledge-base document, not configuration",
        )),
        GraphName::NamedNode(NamedNode::new(&kb_graph).expect("kb graph IRI is valid")),
    )
}

// ── Item 1: a full copy ──────────────────────────────────────────────────────────────────────

/// Every triple from every record kind in the source's CONFIG_GRAPH must appear in the config
/// store afterwards -- checked as an exact set, and the migrated set's distinct subjects must
/// include all five fixture records, so a migration that copies only the first subject and stops
/// fails this test rather than passing on a coincidentally matching count.
#[test]
fn full_copy_moves_every_triple_from_every_record_kind() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    let source_triples = build_combined_store(&combined_path);
    assert!(
        source_triples.len() > 10,
        "fixture must contain more than a trivial number of triples: {}",
        source_triples.len()
    );

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    let outcome = migrate_config_graph_if_needed(&combined_path, &config_store)
        .expect("migrating a fresh config store from a populated combined store succeeds");

    match outcome {
        MigrationOutcome::Migrated { triples_copied } => {
            assert_eq!(
                triples_copied,
                source_triples.len(),
                "the reported copied count must equal the source's own CONFIG_GRAPH triple count"
            );
        }
        other => panic!("expected MigrationOutcome::Migrated, got {other:?}"),
    }

    let migrated_triples = config_graph_triples(config_store.inner());
    assert_eq!(
        migrated_triples, source_triples,
        "every triple in the source's CONFIG_GRAPH must appear in the config store afterwards, \
         and nothing else must"
    );

    let subjects = distinct_subjects(&migrated_triples);
    assert!(
        subjects.len() >= 5,
        "expected at least 5 distinct subjects (company, connector, kg instance, knowledge \
         base, agent) to have survived the copy, got {}: {subjects:?}",
        subjects.len()
    );
}

// ── Item 2: the source is left intact ────────────────────────────────────────────────────────

/// Migration copies; it does not move or delete. Re-opened after the migration call returns
/// (migration's own handle on the combined store must not still be held, or this reopen would
/// fail outright -- the on-disk backend does not support two live handles on one path from one
/// process), the source's CONFIG_GRAPH must be byte-identical to what it held before.
#[test]
fn source_combined_store_is_left_intact_after_migration() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    let source_triples_before = build_combined_store(&combined_path);

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    migrate_config_graph_if_needed(&combined_path, &config_store).expect("migration succeeds");

    let reopened_source =
        Store::open(&combined_path).expect("the combined store must still be openable afterwards");
    let source_triples_after = config_graph_triples(&reopened_source);

    assert_eq!(
        source_triples_after, source_triples_before,
        "the combined store's own CONFIG_GRAPH must be unchanged by migration -- copy, not move"
    );
}

// ── Item 3: verification catches an incomplete copy ─────────────────────────────────────────

/// Control: verification must report success -- naming how many triples it checked -- when the
/// copy genuinely is complete. Paired with the rejection test below per this task's own trap
/// warning: a check that always fails would "catch" the corrupted case too, so this control
/// proves the check isn't merely inverted.
#[test]
fn verify_config_graph_copy_succeeds_when_the_copy_is_actually_complete() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    let source_triples = build_combined_store(&combined_path);

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    migrate_config_graph_if_needed(&combined_path, &config_store).expect("migration succeeds");

    let reopened_source = Store::open(&combined_path).expect("the combined store reopens");
    let verified = verify_config_graph_copy(&reopened_source, &config_store)
        .expect("verifying a genuinely complete copy must succeed");
    assert_eq!(
        verified,
        source_triples.len(),
        "the verified count must equal the source's own triple count"
    );
}

/// Deliberately constructs the incomplete case rather than trusting the copy path to be perfect
/// (this task's own instruction): after a real, successful migration, one triple is removed
/// directly from the config store -- simulating exactly what an interrupted or partially-failed
/// copy would leave behind -- and `verify_config_graph_copy` is called directly against that
/// corrupted target. It must return a *named error*, not a warning and not `Ok` with a lower
/// count silently accepted.
///
/// This is what would catch a verification routine that "examines nothing [and] still reports
/// success" (this task's trap warning, restated from the `list_kg_instances` regression): if
/// `verify_config_graph_copy` merely returned `Ok(_)` unconditionally, or compared nothing at
/// all, this test's `expect_err` would fail outright, because it would receive `Ok` where it
/// demands `Err`.
#[test]
fn verify_config_graph_copy_rejects_an_incomplete_copy_as_a_named_error() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    let source_triples = build_combined_store(&combined_path);

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    migrate_config_graph_if_needed(&combined_path, &config_store).expect("migration succeeds");

    // Deliberately corrupt the target: remove exactly one triple, simulating an interrupted or
    // partially-failed copy -- constructed directly, not by hoping the copy step fails on its
    // own.
    let one_removed_triple = source_triples
        .iter()
        .next()
        .expect("fixture has at least one triple");
    let graph = NamedNode::new(CONFIG_GRAPH).expect("CONFIG_GRAPH is a valid IRI");
    let removed_quad = config_store
        .inner()
        .quads_for_pattern(None, None, None, Some((&graph).into()))
        .collect::<Result<Vec<_>, _>>()
        .expect("reading quads succeeds")
        .into_iter()
        .find(|q| {
            (
                q.subject.to_string(),
                q.predicate.to_string(),
                q.object.to_string(),
            ) == *one_removed_triple
        })
        .expect("the chosen triple exists in the freshly migrated config store");
    config_store
        .inner()
        .remove(&removed_quad)
        .expect("removing exactly one quad from the config store succeeds");

    let reopened_source = Store::open(&combined_path).expect("the combined store reopens");
    let result = verify_config_graph_copy(&reopened_source, &config_store);
    let err = match result {
        Err(e) => e,
        Ok(count) => panic!(
            "verify_config_graph_copy must return Err for a config store missing one of the \
             source's {} triples, but it returned Ok({count}) -- a partial copy must never be \
             reported as verified",
            source_triples.len()
        ),
    };

    let message = err.to_string();
    let expected_total = source_triples.len();
    let expected_found = source_triples.len() - 1;
    assert!(
        message_contains_number(&message, expected_total)
            && message_contains_number(&message, expected_found),
        "the error {message:?} must name both the expected total ({expected_total}) and the \
         actual count found ({expected_found}), so an operator can see exactly how incomplete \
         the copy was -- not just that something was wrong"
    );
}

// ── Item 4: idempotent ───────────────────────────────────────────────────────────────────────

/// Runs on every startup, so a second run against an already-populated config store must be a
/// true no-op: no error, no duplicate triples, and the data already there is untouched. This is
/// the case where the *first* call was migration itself, not manually seeded data (see the
/// distinct "already populated" tests under item 5 below for that case).
#[test]
fn re_running_migration_against_an_already_migrated_store_is_a_no_op() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    build_combined_store(&combined_path);

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    let first = migrate_config_graph_if_needed(&combined_path, &config_store)
        .expect("first migration succeeds");
    assert!(
        matches!(first, MigrationOutcome::Migrated { .. }),
        "the first call against a fresh config store must actually migrate, got {first:?}"
    );
    let triples_after_first = config_graph_triples(config_store.inner());

    let second = migrate_config_graph_if_needed(&combined_path, &config_store)
        .expect("re-running migration must never error");
    assert!(
        !matches!(second, MigrationOutcome::Migrated { .. }),
        "a second run against an already-migrated config store must not report a fresh \
         migration, got {second:?}"
    );

    let triples_after_second = config_graph_triples(config_store.inner());
    assert_eq!(
        triples_after_second, triples_after_first,
        "a second run must not duplicate triples or otherwise change what the first run wrote"
    );
}

// ── Item 5: the cases where nothing should happen, each distinctly ─────────────────────────

/// Case one: the config store already has data of its own (never migrated from anywhere -- e.g.
/// hand-entered, or seeded before this feature existed). The combined store, distinctly, holds
/// *different* data. Migration must not merge the combined store's data in, must not error, and
/// must leave the config store's own pre-existing data exactly as it was.
#[test]
fn config_store_already_populated_is_left_untouched_and_combined_data_is_not_merged_in() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    build_combined_store(&combined_path);

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    // Seed the config store directly -- distinct company from the combined store's "acme", so a
    // merge (rather than a true no-op) would be visible.
    let cg = ConfigGraph::new(&config_store, ConnectorDeclarations::none());
    cg.add_company(&CompanyConfig {
        slug: "already-here".to_string(),
        name: "Already Here Inc".to_string(),
    })
    .expect("seeding the config store directly succeeds");
    let triples_before = config_graph_triples(config_store.inner());
    assert!(
        !triples_before.is_empty(),
        "the config store must genuinely have data before migration runs"
    );

    let outcome = migrate_config_graph_if_needed(&combined_path, &config_store)
        .expect("migration against an already-populated config store must not error");
    assert!(
        !matches!(outcome, MigrationOutcome::Migrated { .. }),
        "an already-populated config store must not be reported as freshly migrated, got \
         {outcome:?}"
    );

    let triples_after = config_graph_triples(config_store.inner());
    assert_eq!(
        triples_after, triples_before,
        "the config store's own pre-existing data must be exactly what it was -- the combined \
         store's distinct 'acme' company must not have been merged in"
    );
    let subjects_after = distinct_subjects(&triples_after);
    assert!(
        subjects_after
            .iter()
            .all(|s| !s.contains("acme") && !s.contains("main")),
        "no subject from the combined store's fixture ('acme', 'main') may appear in a config \
         store that already had its own data: {subjects_after:?}"
    );
}

/// Case two: no store exists at all at `combined_store_path` -- a brand-new deployment that
/// never had a combined store, or one that was never populated. Must not error, must not
/// fabricate a store there (Oxigraph's `Store::open` would otherwise silently create one at any
/// path handed to it -- if migration opened it unconditionally without checking existence first,
/// this test would still observe an empty config store, but a fresh empty Oxigraph store
/// directory would now exist where nothing should), and the config store must remain empty.
#[test]
fn combined_store_missing_entirely_is_a_clean_no_op() {
    let combined_dir = tempfile::tempdir().expect("tempdir, never populated");
    let combined_path = combined_dir.path().join("graph_store");
    assert!(
        !combined_path.exists(),
        "precondition: nothing must exist at the combined store path yet"
    );

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    let outcome = migrate_config_graph_if_needed(&combined_path, &config_store)
        .expect("a missing combined store must not be an error");
    assert!(
        !matches!(outcome, MigrationOutcome::Migrated { .. }),
        "nothing exists to migrate from, so this must not report a migration, got {outcome:?}"
    );
    assert!(
        config_graph_triples(config_store.inner()).is_empty(),
        "the config store must remain empty when there was nothing to migrate from"
    );
    assert!(
        !combined_path.exists(),
        "migration must not fabricate a store at a path where none existed -- a caller checking \
         whether a combined store exists (e.g. to decide whether to show a first-run experience) \
         must not be misled by migration's own side effects"
    );
}

/// Case three: a combined store exists at the path (some other process, or an earlier
/// unconfigured run, already created it) but holds no config graph at all -- e.g. it holds only
/// knowledge-graph data, or is a genuinely empty store. Must not error, and must not produce a
/// partial store.
#[test]
fn combined_store_exists_but_holds_no_config_graph_is_a_clean_no_op() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    {
        // Create the store and write only KG-data (never CONFIG_GRAPH) into it, then drop the
        // handle before migration opens its own.
        let store = Store::open(&combined_path).expect("combined store opens");
        store
            .insert(&kg_data_quad())
            .expect("inserting KG-only data succeeds");
        drop(store);
    }

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    let outcome = migrate_config_graph_if_needed(&combined_path, &config_store)
        .expect("a combined store with no config graph must not be an error");
    assert!(
        !matches!(outcome, MigrationOutcome::Migrated { .. }),
        "there is no config graph to migrate, so this must not report a migration, got \
         {outcome:?}"
    );
    assert!(
        config_graph_triples(config_store.inner()).is_empty(),
        "the config store must remain empty when the combined store held no config graph"
    );
}

/// A nuance of case one: D6 (contreforts-workspace#58) reloads the reserved product graph into
/// the config store at every startup, from the binary's own compiled-in data -- independent of
/// this migration, and very possibly having already run by the time migration runs (ordering
/// between the two is left for part 2b to decide; see the task report). A config store holding
/// *only* product-graph data must not be mistaken for "already migrated" -- if it were, a
/// deployment where the product-graph reload happens first would never receive its real,
/// hand-entered configuration at all, which is precisely the data-loss this feature exists to
/// prevent.
#[test]
fn product_graph_data_alone_does_not_count_as_an_already_populated_config_store() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    let source_triples = build_combined_store(&combined_path);

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));
    config_store
        .reload_product_graph(
            r#"
            @prefix sh: <http://www.w3.org/ns/shacl#> .
            @prefix ex: <https://contreforts.ds-labs.org/ontologies/example#> .
            ex:ExampleShape a sh:NodeShape .
        "#,
        )
        .expect("loading the reserved product graph succeeds");

    let outcome = migrate_config_graph_if_needed(&combined_path, &config_store)
        .expect("migration must still run when only the reserved product graph is populated");
    match outcome {
        MigrationOutcome::Migrated { triples_copied } => {
            assert_eq!(triples_copied, source_triples.len());
        }
        other => panic!(
            "product-graph-only data must not be mistaken for an already-migrated config \
             store: expected MigrationOutcome::Migrated, got {other:?}"
        ),
    }
    assert_eq!(
        config_graph_triples(config_store.inner()),
        source_triples,
        "the real configuration must have been copied in, exactly"
    );
}

// ── Item 6: only the config graph moves ─────────────────────────────────────────────────────

/// The combined store also holds knowledge-graph data (that is the entire reason it needs
/// splitting) -- that data must never reach the config store, in any graph.
#[test]
fn kg_data_in_the_combined_store_is_never_copied_into_the_config_store() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    build_combined_store(&combined_path);

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    migrate_config_graph_if_needed(&combined_path, &config_store).expect("migration succeeds");

    let target_quads = all_quads(config_store.inner());
    let kg_quad = kg_data_quad();
    assert!(
        !target_quads.contains(&kg_quad),
        "the KG-data triple from the combined store's non-CONFIG_GRAPH graph must not appear \
         anywhere in the config store: {target_quads:?}"
    );
    assert!(
        !target_quads.iter().any(|q| q.graph_name
            != GraphName::NamedNode(
                NamedNode::new(CONFIG_GRAPH).expect("CONFIG_GRAPH is a valid IRI")
            )),
        "every quad written into the config store by migration must live under CONFIG_GRAPH -- \
         found one in another graph: {target_quads:?}"
    );
}

// ── Adversarial review item 1: count equality is not content equality ──────────────────────

/// `verify_config_graph_copy`'s error names `expected`/`found` as bare counts, which -- read on
/// its own -- looks like it might only ever compare lengths. It does not: it checks that every
/// one of the source's quads is individually present in the target (set containment), so a
/// same-*count* copy whose *content* differs must still be rejected. Constructed directly rather
/// than trusted from the implementation reading correct: after a real, successful migration, one
/// genuine triple is swapped out of the config store for one fabricated, unrelated triple under
/// CONFIG_GRAPH -- so the target's total CONFIG_GRAPH triple count is identical to the source's,
/// but its content is not. A verification that only compared `store.len()` to `store.len()` would
/// pass this; the real one must not.
#[test]
fn verify_config_graph_copy_rejects_a_same_count_but_different_content_copy() {
    let combined_dir = tempfile::tempdir().expect("tempdir for combined store");
    let combined_path = combined_dir.path().join("graph_store");
    let source_triples = build_combined_store(&combined_path);

    let config_dir = tempfile::tempdir().expect("tempdir for config store");
    let config_store = config_store_at(&config_dir.path().join("config_store"));

    migrate_config_graph_if_needed(&combined_path, &config_store).expect("migration succeeds");

    let graph = NamedNode::new(CONFIG_GRAPH).expect("CONFIG_GRAPH is a valid IRI");

    // Remove one genuine triple...
    let removed_triple = source_triples
        .iter()
        .next()
        .expect("fixture has at least one triple");
    let removed_quad = config_store
        .inner()
        .quads_for_pattern(None, None, None, Some((&graph).into()))
        .collect::<Result<Vec<_>, _>>()
        .expect("reading quads succeeds")
        .into_iter()
        .find(|q| {
            (
                q.subject.to_string(),
                q.predicate.to_string(),
                q.object.to_string(),
            ) == *removed_triple
        })
        .expect("the chosen triple exists in the freshly migrated config store");
    config_store
        .inner()
        .remove(&removed_quad)
        .expect("removing exactly one quad from the config store succeeds");

    // ...and insert one fabricated, unrelated triple in its place, under CONFIG_GRAPH, so the
    // total count is restored to exactly what it was before the swap.
    let fabricated_quad = Quad::new(
        NamedNode::new("https://contreforts.ds-labs.org/data/company/not-a-real-company")
            .expect("fabricated subject IRI is valid"),
        NamedNode::new(format!("{CORE_NS}slug")).expect("predicate IRI is valid"),
        Term::Literal(Literal::new_simple_literal("not-a-real-company")),
        GraphName::NamedNode(graph.clone()),
    );
    config_store
        .inner()
        .insert(&fabricated_quad)
        .expect("inserting the fabricated quad succeeds");

    let target_count_after_swap = config_graph_triples(config_store.inner()).len();
    assert_eq!(
        target_count_after_swap,
        source_triples.len(),
        "precondition: the swap must leave the target's CONFIG_GRAPH triple count exactly equal \
         to the source's -- otherwise this is not testing count-equality-with-differing-content \
         at all"
    );

    let reopened_source = Store::open(&combined_path).expect("the combined store reopens");
    let result = verify_config_graph_copy(&reopened_source, &config_store);
    let err = match result {
        Err(e) => e,
        Ok(count) => panic!(
            "verify_config_graph_copy must return Err when the target's CONFIG_GRAPH has the \
             same triple count ({count}) as the source but different content (one real triple \
             swapped for one fabricated one) -- a verification that can be satisfied by the \
             wrong bytes is worthless for data nothing can regenerate"
        ),
    };
    assert!(
        matches!(
            err,
            contreforts_config::ConfigStoreError::ConfigGraphCopyIncomplete { .. }
        ),
        "expected ConfigGraphCopyIncomplete, got {err:?}"
    );
}
